package demo.crm.controller;

import demo.crm.dto.ChatRequest;
import demo.crm.dto.ChatResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.Valid;

@RestController
@RequestMapping("/api/v1/crm")
@Validated
public class CrmChatController {

    private static final Logger log = LoggerFactory.getLogger(CrmChatController.class);

    private final ChatClient chatClient;

    public CrmChatController(ChatClient chatClient) {
        this.chatClient = chatClient;
    }

    @PostMapping("/chat")
    public ResponseEntity<ChatResponse> chat(@Valid @RequestBody ChatRequest request) {
        log.info("CRM query received: {}", request.message());
        try {
            String answer = chatClient.prompt()
                .user(request.message())
                .call()
                .content();
            log.info("CRM answer generated by LLM with context supplied by QuestionAnswerAdvisor: {}", answer);
            return ResponseEntity.ok(new ChatResponse(answer));
        } catch (RuntimeException exception) {
            log.error("CRM chat failed because VectorStore or LLM is unavailable", exception);
            return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE)
                .body(new ChatResponse("Dịch vụ trợ lý CRM tạm thời không khả dụng. Vui lòng thử lại sau."));
        }
    }
}
